package com.kerwin.apps.cms.dao;

import com.kerwin.apps.cms.bean.Privilege;
import com.kerwin.apps.cms.bean.PrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    long countByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int deleteByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int insert(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int insertSelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    List<Privilege> selectByExampleWithBLOBs(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    List<Privilege> selectByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    Privilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByPrimaryKeyWithBLOBs(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByPrimaryKey(Privilege record);
}