package com.kerwin.apps.cms.dao;

import com.kerwin.apps.cms.bean.Role_Privilege;
import com.kerwin.apps.cms.bean.Role_PrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Role_PrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    long countByExample(Role_PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int deleteByExample(Role_PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int insert(Role_Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int insertSelective(Role_Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    List<Role_Privilege> selectByExample(Role_PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    Role_Privilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Role_Privilege record, @Param("example") Role_PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Role_Privilege record, @Param("example") Role_PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Role_Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_privilege
     *
     * @mbg.generated Tue Nov 12 10:21:29 GMT+08:00 2019
     */
    int updateByPrimaryKey(Role_Privilege record);
}