package com.kerwin.apps.cms.dao;

import com.kerwin.apps.cms.bean.User_Role;
import com.kerwin.apps.cms.bean.User_RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface User_RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    long countByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    int deleteByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    int insert(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    int insertSelective(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    List<User_Role> selectByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    User_Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") User_Role record, @Param("example") User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    int updateByExample(@Param("record") User_Role record, @Param("example") User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role
     *
     * @mbg.generated Tue Nov 12 10:21:28 GMT+08:00 2019
     */
    int updateByPrimaryKey(User_Role record);
}